BLACK = (0,0,0)
FPS = 60
TILE = 30
NUM_COLUMN = 40
NUM_ROWS = 20
RES = WIDTH, HEIGHT = TILE*NUM_COLUMN, TILE*NUM_ROWS
PLAYER_COLOR = 'GREEN'
ENEMY_COLOR = 'Red'
chars_ = []
turn = 'player'
MAX_PLAYER_HEALTH = 10
MAX_ENEMY_HEALTH = 10